# Enable or disable the plugin
"enabled": true

# List of worlds where the plugin is disabled
"disabled-worlds": [ ]

# List of items that are not allowed to be disenchanted
"disabled-items": [ ]

# List of enchantments that are not allowed to be disenchanted
"disabled-enchantments": [ ]

# Enable or disable the anvil sound
"enable-anvil-sound": true

# Edit the volume and pitch of the anvil sound
"anvil-volume": 1.0
"anvil-pitch": 1.0

# Enable or disable the repair cost
"enable-repair-cost": true

# Base value for the cost of the disenchantment
"base": 10

# This multiplication is applied to the base value
# ---
# It is calculated by the following:
#   base + (level * multiply)
# ---
# Example: base = 10, sharpness = 5, knockback = 1, multiply = 0.25
# The enchantments are sorted by level in descending order, so the more enchantments you have, the more expensive it is.
#   10 + (1 * 1) = 11
#   15 + (5 * 1.25) = 17.25
#   17.25
# Multiplication value from 0 to infinity (0.25 = 25%) for the cost of the disenchantment
"multiply": 0.25
